# Auto-merge Allowlist for Pin Upgrade PRs
#
# This file controls which servers are eligible for automatic merging when
# their pin upgrade PRs pass all required checks.
#
# Only add servers to this list after verifying they meet these criteria:
# - Stable build process with consistent success rate
# - Comprehensive test coverage
# - Low risk of breaking changes from upstream updates
#
# To add a server to the allowlist:
# 1. Review recent pin update PRs for any issues
# 2. Add the server name to the list below
# 3. Monitor the first few auto-merges closely
#
# To block auto-merge for a specific PR, add the 'skip-auto-merge' label

servers:
  # Known publisher servers from Docker Desktop's known-publisher-server-ids.ts
  # These servers are maintained by verified publishers and eligible for auto-merge

  # Remote servers (66 servers)
  - apify
  - asana
  - astro-docs
  - audioscrape
  - carbon-voice
  - close
  - cloudflare-ai-gateway
  - cloudflare-audit-logs
  - cloudflare-autorag
  - cloudflare-browser-rendering
  - cloudflare-container
  - cloudflare-digital-experience-monitoring
  - cloudflare-dns-analytics
  - cloudflare-docs
  - cloudflare-graphql
  - cloudflare-logpush
  - cloudflare-observability
  - cloudflare-one-casb
  - cloudflare-radar
  - cloudflare-workers-bindings
  - cloudflare-workers-builds
  - dappier-remote
  - deepwiki
  - dialer
  - dodo-payments
  - find-a-domain
  - firefly
  - gitmcp
  - globalping
  - grafbase
  - hubspot
  - hugging-face
  - instant
  - invideo
  - javadocs
  - linear
  - llmtxt
  - manifold
  - mercado-libre
  - mercado-pago
  - microsoft-learn
  - monday
  - needle
  - notion-remote
  - octagon
  - openmesh
  - openzeppelin-cairo
  - openzeppelin-solidity
  - openzeppelin-stellar
  - openzeppelin-stylus
  - paypal
  - polar-signals
  - prisma-postgres
  - pulumi-remote
  - remote-mcp
  - rube
  - scorecard
  - semgrep
  - sentry-remote
  - short-io
  - stripe-remote
  - telnyx
  - wayfound
  - waystation
  - webflow-remote
  - wix

  # Local servers (101 servers)
  - aks
  - apify-mcp-server
  - apollo-mcp-server
  - astra-db
  - atlan
  - atlas-docs
  - audiense-insights
  - aws-cdk-mcp-server
  - aws-core-mcp-server
  - aws-diagram
  - aws-documentation
  - aws-terraform
  - azure
  - beagle-security
  - bitrefill
  - brave
  - browserbase
  - buildkite
  - cdata-connectcloud
  - charmhealth-mcp-server
  - chroma
  - clickhouse
  - cloud-run-mcp
  - context7
  - couchbase
  - cyreslab-ai-shodan
  - dappier
  - dart
  - databutton
  - descope
  - desktop-commander
  - devhub-cms
  - dockerhub
  - dreamfactory-mcp
  - dynatrace-mcp-server
  - e2b
  - edubase
  - elasticsearch
  - elevenlabs
  - exa
  - explorium
  - fibery
  - github-official
  - glif
  - grafana
  - hackle
  - handwriting-ocr
  - heroku
  - hummingbot-mcp
  - hyperbrowser
  - hyperspell
  - iaptic
  - inspektor-gadget
  - kagisearch
  - keboola-mcp
  - kong
  - line
  - maestro-mcp-server
  - mapbox
  - mapbox-devkit
  - markitdown
  - mongodb
  - multiversx-mx
  - neo4j-cloud-aura-api
  - neo4j-cypher
  - neo4j-data-modeling
  - neo4j-memory
  - neon
  - notion
  - novita
  - onlyoffice-docspace
  - oxylabs
  - perplexity-ask
  - pia
  - pinecone
  - playwright
  - pulumi
  - quantconnect
  - razorpay
  - redis
  - redis-cloud
  - ref
  - render
  - schemacrawler-ai
  - scrapezy
  - sec-edgar
  - singlestore
  - smartbear
  - sonarqube
  - stackhawk
  - stripe
  - supadata
  - tavily
  - teamwork
  - terraform
  - thingsboard
  - tigris
  - triplewhale
  - uberall
