version: "3"

tasks:
  create:
    desc: Create a new mcp server definition
    cmd: go run ./cmd/create {{.CLI_ARGS}}

  build:
    desc: Build a server image
    cmd: go run ./cmd/build {{.CLI_ARGS}}

  catalog:
    desc: Generate a test catalog
    cmd: go run ./cmd/catalog {{.CLI_ARGS}}

  wizard:
    desc: Run the wizard
    cmd: go run ./cmd/wizard {{.CLI_ARGS}}

  remote-wizard:
    desc: Run the remote server wizard
    cmd: go run ./cmd/remote-wizard {{.CLI_ARGS}}

  validate:
    desc: Validate a server
    cmd: go run ./cmd/validate {{.CLI_ARGS}}

  clean:
    desc: Clean build artifacts for servers
    cmd: go run ./cmd/clean {{.CLI_ARGS}}

  ci:
    desc: Run CI helper utilities
    cmd: go run ./cmd/ci {{.CLI_ARGS}}

  import:
    desc: Import a server into the registry
    cmd: docker mcp catalog import ./catalogs/{{.CLI_ARGS}}/catalog.yaml

  reset:
    desc: Reset the catalog
    cmds:
      - docker mcp catalog reset
      - docker mcp catalog init

  unittest:
    desc: Run Go unit tests
    cmd: go test ./...

  security-reviewer:
    desc: Run the security reviewer agent
    cmd: go run ./cmd/security-reviewer {{.CLI_ARGS}}
